# Generated by Django 3.1.6 on 2021-03-05 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop_tags', '0001_initial'),
        ('companion_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('binomial_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=600)),
                ('is_perennial', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=300)),
                ('growing_days', models.PositiveIntegerField()),
                ('sowing_method', models.TextField(max_length=400)),
                ('companions', models.ManyToManyField(blank=True, related_name='crops', to='companion_groups.CompanionGroup')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_crop', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_crops', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='crops', to='crop_tags.CropTag')),
            ],
        ),
    ]
