# Generated by Django 3.1.6 on 2021-02-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companion_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('binomial_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=600)),
                ('is_perennial', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=300)),
                ('growing_days', models.PositiveIntegerField()),
                ('sowing_method', models.TextField(max_length=400)),
                ('companions', models.ManyToManyField(blank=True, related_name='crops', to='companion_groups.CompanionGroup')),
            ],
        ),
    ]
