# Generated by Django 3.1.5 on 2021-01-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_tags', '0001_initial'),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='tags',
            field=models.ManyToManyField(related_name='crops', to='crop_tags.CropTag'),
        ),
    ]
